In [1]:
import os
import shutil
import pandas as pd

In [2]:
# function to check number of images in folders
import os

def count_images_in_directory(directory):
    """
    Count the number of image files in a directory.
    """
    image_extensions = ['.jpg', '.jpeg', '.png', '.gif', '.bmp']  # Add more extensions if needed
    image_count = 0

    # Iterate through all files in the directory
    for file_name in os.listdir(directory):
        file_path = os.path.join(directory, file_name)

        # Check if the file is a regular file (not a directory)
        if os.path.isfile(file_path):
            # Check if the file has a recognized image extension
            if any(file_name.lower().endswith(ext) for ext in image_extensions):
                image_count += 1

    return image_count

def count_images_in_all_directories(root_directory):
    """
    Count the number of image files in all directories and subdirectories.
    """
    total_image_count = 0

    # Walk through all directories and subdirectories
    for dirpath, dirnames, filenames in os.walk(root_directory):
        # Count the number of image files in the current directory
        current_dir_image_count = count_images_in_directory(dirpath)

        # Add the count to the total image count
        total_image_count += current_dir_image_count

        # Print the directory path and the number of images
        #print(f"Directory: {dirpath}, Images: {current_dir_image_count}")

    return total_image_count

### ADULTS: Only move files from RFW full also in balanced adulst csv folder
**OBS: to file structure as child data**

In [3]:
#adults_csv = pd.read_csv('../data/adults_balanced.csv')
# adults_csv = pd.read_csv('/Users/gabriellakierulff/Desktop/HCAI/speciale/Master_Thesis/data/adults_balanced.csv')
adults_csv = pd.read_csv('../../data/image_info_csvs/final_filtered_adults_df_BIBEL.csv')
len(adults_csv)

26263

In [4]:
adults_csv

,Unnamed: 0,files_list,image_name,identity_name,enrolled,ethnicity,Age,Identity,UnifiedQualityScore.scalar,HeadPoseYaw.scalar,HeadPosePitch.scalar,HeadPoseRoll.scalar,children_agegroup
0,0,African_m.010lz5/m.010lz5_0001.jpg,m.010lz5_0001,m.010lz5,enrolled,African,38,m.010lz5,35,100,100,100,NaN
1,1,African_m.010lz5/m.010lz5_0002.jpg,m.010lz5_0002,m.010lz5,enrolled,African,29,m.010lz5,40,76,81,97,NaN
2,2,African_m.010lz5/m.010lz5_0003.jpg,m.010lz5_0003,m.010lz5,enrolled,African,37,m.010lz5,34,99,76,100,NaN
3,3,African_m.011y5k/m.011y5k_0001.jpg,m.011y5k_0001,m.011y5k,enrolled,African,40,m.011y5k,5,90,100,100,NaN
4,4,African_m.011y5k/m.011y5k_0002.jpg,m.011y5k_0002,m.011y5k,enrolled,African,43,m.011y5k,51,100,100,100,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26258,39348,Indian_m.0tj9/m.0tj9_0004.jpg,m.0tj9_0004,m.0tj9,enrolled,Indian,46,m.0tj9,35,60,91,96,NaN
26259,39349,Indian_m.0tj9/m.0tj9_0005.jpg,m.0tj9_0005,m.0tj9,enrolled,Indian,48,m.0tj9,71,92,99,100,NaN
26260,39350,Indian_m.0t_d791/m.0t_d791_0001.jpg,m.0t_d791_0001,m.0t_d791,enrolled,Indian,21,m.0t_d791,20,74,58,84,NaN
26261,39351,Indian_m.0t_d791/m.0t_d791_0002.jpg,m.0t_d791_0002,m.0t_d791,enrolled,Indian,20,m.0t_d791,17,77,98,99,NaN
26262,39352,Indian_m.0t_d791/m.0t_d791_0003.jpg,m.0t_d791_0003,m.0t_d791,enrolled,Indian,26,m.0t_d791,45,87,99,100,NaN

In [5]:
adults_csv[adults_csv['image_name']=="m.023915"]

Empty DataFrame
Columns: [Unnamed: 0, files_list, image_name, identity_name, enrolled, ethnicity, Age, Identity, UnifiedQualityScore.scalar, HeadPoseYaw.scalar, HeadPosePitch.scalar, HeadPoseRoll.scalar, children_agegroup]
Index: []

In [9]:
def move_adults(image_dir, dst_root):
    image_file_names = adults_csv['image_name'].tolist()

    # Get the list of folders in the image directory
    folders = [os.path.join(image_dir, d) for d in os.listdir(image_dir) if os.path.isdir(os.path.join(image_dir, d))]
    print(folders)
    # Iterate through each folder
    for folder in folders:
        # Get the list of subfolders
        folders2 = [os.path.join(folder, d) for d in os.listdir(folder) if os.path.isdir(os.path.join(folder, d))]
        for folder2 in folders2:
        # Get the list of image files in the folder
            files = [f for f in os.listdir(folder2) if os.path.isfile(os.path.join(folder2, f))]

            # Check if any of the images from folder are in filtered CSV 
            for file in files:
                if file[:-4] in image_file_names:
                    # Move the image file to the output directory

                    # Make folder with ethnicityname_imageid
                    folder2_add = folder2.split("/")[-2:]
                    folder2_add_real = '_'.join(folder2_add)

                    dst_root = dst_root
                    src = os.path.join(folder2, file)
                    dst = os.path.join(dst_root, folder2_add_real)
                    os.makedirs(dst,exist_ok=True)
                    shutil.copy(src, dst)
    print('Done moving files')

In [10]:

image_dir = '../../data/data_full/RFW/data'
dst_root = '../../data/data_full/adults_full_filtered_age_std' #../data/raw_full/adults'

### Only run if you need to move data

move_adults(image_dir, dst_root)

['../../data/data_full/RFW/data/Indian', '../../data/data_full/RFW/data/African', '../../data/data_full/RFW/data/Caucasian', '../../data/data_full/RFW/data/Asian']
Done moving files

In [11]:
## Check number of images in folder
root_directory = '../../data/data_full/adults_full_filtered_age_std'
total_images = count_images_in_all_directories(root_directory)
print(f"Total number of images: {total_images}")

Total number of images: 26286

In [6]:
# Where's the duplicates?

# Function to find duplicate file names within a folder and remove the first instance
def remove_first_instance_of_duplicate_file_names(folder_path):
    file_names = {}  # Dictionary to store file names and their counts

    # Traverse each folder recursively
    for root, dirs, files in os.walk(folder_path):
        for file_name in files:
            file_path = os.path.join(root, file_name)
            # Increment count for file name in dictionary
            # if file_name in file_names:
            #     # If the file name already exists, delete the first occurrence
            #     os.remove(file_path)
            #     print(f"Removed first instance of duplicate file: {file_path}")
            # else:
            #     file_names[file_name] = file_path

            if file_name in file_names:
                # If the file name already exists, remove the entire containing folder
                os.system(f"rm -rf '{os.path.dirname(file_path)}'")
                print(f"Removed folder containing duplicate file: {os.path.dirname(file_path)}")
                break  # Once a duplicate is found and removed, exit the loop
            else:
                file_names[file_name] = file_path

# Main function to check for duplicate file names in all folders
def check_for_duplicate_file_names_and_remove_first_instance(root_folder):
    for root, dirs, files in os.walk(root_folder):
        #print(f"Checking duplicates in folder: {root}")
        remove_first_instance_of_duplicate_file_names(root)

# Example usage:
root_folder = '../../data/data_full/adults_full_filtered_age_std'
check_for_duplicate_file_names_and_remove_first_instance(root_folder)

In [18]:
## Check number of images in folder now
root_directory = '../../data/data_full/adults_full_filtered_age_std'
total_images = count_images_in_all_directories(root_directory)
print(f"Total number of images: {total_images}") # should be 3306
print("same as in dataframe?:", len(adults_csv))

Total number of images: 26257
same as in dataframe?: 26263

### CHILDREN: Only move files from YLFW full and RFW full also in balanced children csv folder

In [7]:
children_df = pd.read_csv('../../data/image_info_csvs/final_filtered_children_df_BIBEL.csv')
len(children_df)

7817

In [8]:
children_df

,Unnamed: 0,files_list,image_name,enrolled,identity_name,ethnicity,Age,Identity,UnifiedQualityScore.scalar,HeadPoseYaw.scalar,HeadPosePitch.scalar,HeadPoseRoll.scalar,children_agegroup
0,0,African_0/African_0_0.png,African_0_0,enrolled,African_0,African,7,African_0,34.0,100.0,93.0,100.0,7-9
1,1,African_1/African_1_11.png,African_1_11,enrolled,African_1,African,5,African_1,65.0,100.0,99.0,100.0,4-6
2,2,African_1/African_1_4.png,African_1_4,enrolled,African_1,African,2,African_1,23.0,95.0,99.0,100.0,1-3
3,3,African_10/African_10_1.png,African_10_1,enrolled,African_10,African,5,African_10,50.0,100.0,97.0,100.0,4-6
4,4,African_10/African_10_3.png,African_10_3,enrolled,African_10,African,6,African_10,25.0,90.0,100.0,100.0,4-6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7812,7812,Indian_m.0h9448x/m.0h9448x_0002.jpg,m.0h9448x_0002,enrolled,m.0h9448x,Indian,14,m.0h9448x,86.0,100.0,100.0,100.0,13-15
7813,7813,Indian_m.0hncksb/m.0hncksb_0003.jpg,m.0hncksb_0003,enrolled,m.0hncksb,Indian,11,m.0hncksb,20.0,96.0,94.0,100.0,10-12
7814,7814,Indian_m.0j63px2/m.0j63px2_0003.jpg,m.0j63px2_0003,enrolled,m.0j63px2,Indian,12,m.0j63px2,88.0,99.0,98.0,100.0,10-12
7815,7815,Indian_m.0j63px2/m.0j63px2_0004.jpg,m.0j63px2_0004,enrolled,m.0j63px2,Indian,15,m.0j63px2,24.0,64.0,98.0,99.0,13-15
7816,7816,Indian_m.0jwwdq1/m.0jwwdq1_0002.jpg,m.0jwwdq1_0002,enrolled,m.0jwwdq1,Indian,6,m.0jwwdq1,17.0,98.0,98.0,100.0,4-6

In [9]:
children_df[children_df["image_name"].str.contains('\.')]

,Unnamed: 0,files_list,image_name,enrolled,identity_name,ethnicity,Age,Identity,UnifiedQualityScore.scalar,HeadPoseYaw.scalar,HeadPosePitch.scalar,HeadPoseRoll.scalar,children_agegroup
1498,1498,African_m.02664bd/m.02664bd_0001.jpg,m.02664bd_0001,enrolled,m.02664bd,African,9,m.02664bd,25.0,99.0,98.0,100.0,7-9
1499,1499,African_m.02664bd/m.02664bd_0002.jpg,m.02664bd_0002,enrolled,m.02664bd,African,11,m.02664bd,32.0,96.0,98.0,100.0,10-12
1500,1500,African_m.02z7z7t/m.02z7z7t_0001.jpg,m.02z7z7t_0001,enrolled,m.02z7z7t,African,9,m.02z7z7t,40.0,99.0,97.0,100.0,7-9
1501,1501,African_m.02z7z7t/m.02z7z7t_0002.jpg,m.02z7z7t_0002,enrolled,m.02z7z7t,African,10,m.02z7z7t,17.0,58.0,97.0,98.0,10-12
1502,1502,African_m.02z7z7t/m.02z7z7t_0003.jpg,m.02z7z7t_0003,enrolled,m.02z7z7t,African,14,m.02z7z7t,13.0,99.0,95.0,100.0,13-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7812,7812,Indian_m.0h9448x/m.0h9448x_0002.jpg,m.0h9448x_0002,enrolled,m.0h9448x,Indian,14,m.0h9448x,86.0,100.0,100.0,100.0,13-15
7813,7813,Indian_m.0hncksb/m.0hncksb_0003.jpg,m.0hncksb_0003,enrolled,m.0hncksb,Indian,11,m.0hncksb,20.0,96.0,94.0,100.0,10-12
7814,7814,Indian_m.0j63px2/m.0j63px2_0003.jpg,m.0j63px2_0003,enrolled,m.0j63px2,Indian,12,m.0j63px2,88.0,99.0,98.0,100.0,10-12
7815,7815,Indian_m.0j63px2/m.0j63px2_0004.jpg,m.0j63px2_0004,enrolled,m.0j63px2,Indian,15,m.0j63px2,24.0,64.0,98.0,99.0,13-15
7816,7816,Indian_m.0jwwdq1/m.0jwwdq1_0002.jpg,m.0jwwdq1_0002,enrolled,m.0jwwdq1,Indian,6,m.0jwwdq1,17.0,98.0,98.0,100.0,4-6

In [10]:
import time
def move_file_with_retry(source, destination, max_retries=3, retry_delay=5):
    retries = 0
    while retries < max_retries:
        try:
            shutil.copy(source, destination)
            #print("File moved successfully.")
            return True  # File moved successfully, no need to retry
        except TimeoutError as e:
            print(f"TimeoutError: {e}. Retrying...")
            retries += 1
            time.sleep(retry_delay)
        except FileNotFoundError as e:
            pass
    
    print("Exceeded maximum retries. Moving on to the next task.")
    return False  # Exceeded maximum retries, unable to move the file

In [11]:
# CHILDREN: Only move files from YLFW full and RFW full also in balanced children csv folder
def move_children(image_dir_rfw, image_dir_ylfw, dst_root, children_df):

    # First for RFW
    rfw_csv = children_df[children_df["image_name"].str.contains('\.')]
    image_file_names = rfw_csv['image_name'].tolist()

    # Get the list of folders in the image directory
    folders = [os.path.join(image_dir_rfw, d) for d in os.listdir(image_dir_rfw) if os.path.isdir(os.path.join(image_dir_rfw, d))]
    # Iterate through each folder
    for folder in folders:
        # Get the list of subfolders
        folders2 = [os.path.join(folder, d) for d in os.listdir(folder) if os.path.isdir(os.path.join(folder, d))]
        for folder2 in folders2:
        # Get the list of image files in the folder
            files = [f for f in os.listdir(folder2) if os.path.isfile(os.path.join(folder2, f))]

            # Check if any of the image file names from the CSV are in the folder
            for file in files:
                if file[:-4] in image_file_names:
                    # Move the image file to the output directory

                    # Make folder with ethnicityname_imageid
                    folder2_add = folder2.split("/")[-2:]
                    folder2_add_real = '_'.join(folder2_add)

                    dst_root = dst_root
                    src = os.path.join(folder2, file)
                    dst = os.path.join(dst_root, folder2_add_real)
                    os.makedirs(dst,exist_ok=True)
                    shutil.copy(src, dst)
    print('Done moving RFW files')


    # THEN YLFW
    ylfw_csv = children_df[~children_df["image_name"].str.contains('\.')]
    ylfw_image_file_names = ylfw_csv['image_name'].tolist()

    # Get the list of folders in the image directory
    folders = [os.path.join(image_dir_ylfw, d) for d in os.listdir(image_dir_ylfw) if os.path.isdir(os.path.join(image_dir_ylfw, d))]
    # Iterate through each folder
    for folder in folders:
        # Get the list of image files in the folder
        files = [f for f in os.listdir(folder) if os.path.isfile(os.path.join(folder, f))]
        # Check if any of the image file names from the CSV are in the folder
        for file in files:
            if file[:-4] in ylfw_image_file_names:
                # Move the image file to same foldername in the output directory
                folder_dst = folder.split("/")[-1]

                dst_root = dst_root
                src = os.path.join(folder, file)
                dst = os.path.join(dst_root, folder_dst)
                os.makedirs(dst,exist_ok=True)
                #shutil.copy(src, dst)
                if not move_file_with_retry(src, dst):
                    # Handle the case where the file move operation fails
                    print(f"Failed to move file: {src}")

    print('Done moving YLFW files')

# Example usage:
# children_df = pd.read_csv('/Users/gabriellakierulff/Desktop/HCAI/speciale/Master_Thesis/data/child_balanced.csv')
# image_dir_rfw = "../data/raw_full/RFW/data"
# image_dir_ylfw = "../data/raw_full/YLFW/data_aligned"
# dst_root = "../data/raw_full/children"
# move_children(image_dir_rfw, image_dir_ylfw, dst_root, children_df)

## Check number of images in folder
# root_directory = '../data/raw_full/children'
# total_images = count_images_in_all_directories(root_directory)
# print(f"Total number of images: {total_images}")

In [12]:
image_dir_rfw = '../../data/data_full/RFW/data'
image_dir_ylfw = '../../data/data_full/YLFW/data_aligned'
dst_root = '../../data/data_full/children_full_filtered_age_std'

# Only run if you want to move data

move_children(image_dir_rfw, image_dir_ylfw, dst_root, children_df)

Done moving RFW files

KeyboardInterrupt:

In [34]:
## Check number of images in folder
root_directory = '../../data/data_full/children_full_filtered_age_std'
total_images = count_images_in_all_directories(root_directory)
print(f"Total number of images: {total_images}")
print("same as in dataframe?:", len(children_df))

Total number of images: 311
same as in dataframe?: 7817